loserpool/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from loserpool import views
import django.contrib.auth.views
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^matchups/', include('matchups.urls', namespace="matchups")),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^user_options/$', views.user_options, name='user_options'),
    url(r'^change_password/$', django.contrib.auth.views.password_change, {'template_name':'change_password.html'}, name='password_change'),
    url(r'^password_changed/$', django.contrib.auth.views.password_change_done, {'template_name':'password_changed.html'}),
    url(r'^admin_actions/$', views.admin_actions, name='admin_actions'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

)

matchups/urls.py
from django.conf.urls import patterns, url

from matchups.views import matchup_list, scoreboard, submit_picks, update_scores

urlpatterns = patterns('',
    url(r'^submit', submit_picks.submit_picks_for_current_matchup, name='submit_picks'),
    url(r'^(?P<week_number>\d+)/submit', submit_picks.submit_picks_for_week, name='submit_picks_for_week'),
    url(r'^(?P<week_number>\d+)/(?P<user_id>\d+)/admin_submit', submit_picks.admin_submit_picks_for_week, name='admin_submit_picks_for_week'),
    url(r'^(\d+)/admin_scoreboard', scoreboard.admin_scoreboard_for_week, name='admin_scoreboard_for_week'),
    url(r'^$', scoreboard.scoreboard_current_week, name='scoreboard'),
    url(r'^(\d+)/scoreboard', scoreboard.scoreboard, name='scoreboard_for_week'),
    url(r'^matchup$', matchup_list.current_matchups, name='current_matchups'),
    url(r'^(\d+)/matchup', matchup_list.weekly_matchups, name='weekly_matchups'),
    url(r'^update_scores', update_scores.update_current_scores, name='update_current_scores'),
    url(r'^(\d+)/update_scores', update_scores.update_scores_for_week, name='update_scores_for_week'),
)

teams/urls.py
from django.conf.urls import patterns, url

from teams import views

urlpatterns = patterns('',
    url(r'^$', views.team_manager, name='team_manager'),
)

matchups/models.py
from django.db import models
from teams.models import Team
from django.contrib.auth.models import User
from matchups.matchup_defs import CURRENT_TIMEZONE
import utilities
import pytz

class Matchup(models.Model):
    home_team = models.ForeignKey(Team, related_name="home_team")
    away_team = models.ForeignKey(Team, related_name="away_team")
    home_team_score = models.SmallIntegerField(default=-1)
    away_team_score = models.SmallIntegerField(default=-1)
    date_time = models.DateTimeField()
    
    def date_time_string(self):
        fmt = "%A, %b %d - %I:%M %p"
        return self.date_time.astimezone(pytz.timezone(CURRENT_TIMEZONE)).strftime(fmt)
    
    def full_name(self):
        return self.date_time_string() + ' - ' + self.away_team.full_name() + ' at ' + self.home_team.full_name()
    
    def __unicode__(self): 
        return self.full_name()
    
    def winning_team(self):
        if self.home_team_score < 0 or self.away_team_score < 0:
            return None
        if self.home_team_score > self.away_team_score:
            return self.home_team
        else:
            return self.away_team
    
class PickSet(models.Model):
    user = models.ForeignKey(User)
    letter_id = models.CharField(default='A', max_length='32')
    
    def __unicode__(self):
        if self.user.first_name:
            return self.user.first_name + " - " + self.letter_id
        return self.user.username + " - " + self.letter_id
    
    def is_eliminated(self):
        pick_values = Pick.objects.filter(pick_set__id=self.id).values_list('is_winning_pick', flat=True)
        picked_wrong = True in pick_values 
        minimum_number_of_picks = int(utilities.current_week_number())-1
        missed_a_week = Pick.objects.filter(pick_set__id=self.id).count() < minimum_number_of_picks
        return picked_wrong or missed_a_week

class Pick(models.Model):
    selected_team = models.ForeignKey(Team)
    week_number = models.SmallIntegerField(default=-1)
    pick_set = models.ForeignKey(PickSet)
    is_winning_pick = models.BooleanField(default=False)
    def __unicode__(self): 
        return str(self.pick_set)+ " - Week " + str(self.week_number)

loserpool/views.py
from django.shortcuts import render, redirect
from django import forms
import django.contrib.auth
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import PasswordChangeForm
from matchups.utilities import current_week_number
import matchups.matchup_data_retriever
import teams.team_data_retriever
import teams.models
class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

def login(request):
    redirect_to = request.GET.get('next', None)
    form = LoginForm()
    error_message = ''
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = django.contrib.auth.authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    django.contrib.auth.login(request, user)
                    if redirect_to:
                        return redirect(redirect_to)
                    return render(request, 'successful_login.html')
                else:
                    error_message = "Unable to login due to disabled account."
            else:
                error_message = "Failed to log in. Please try again."
        else:
            error_message = "Failed to log in. Please try again."
    context = {'login_form':form,
               'error_message':error_message,
               'redirect_to':redirect_to}
    return render(request, 'login.html', context)

def logout(request):
    django.contrib.auth.logout(request)
    return render(request, 'successful_logout.html')

def index(request):
    return render(request, "index.html")

@login_required
def user_options(request):
    context = {'week_number':current_week_number()}
    return render(request, "user_options.html", context)

@login_required
def change_password(request):
    error_message = ''
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            print "Change!"
        else:
            error_message = "Failed to change password. Please try again."
    else:
        form = PasswordChangeForm(request.user)
    context = {'form':form,
               'error_message':error_message}
    return render(request, "change_password.html", context)

class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    new_password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    verify_new_password = forms.CharField(max_length=50, widget=forms.PasswordInput)

@permission_required('matchups.add_matchup')
def admin_actions(request):
    if request.method == 'POST':
        if request.POST.has_key('load_matchups'):
            matchups.matchup_data_retriever.MatchupDataRetriever.load_matchups()
        if request.POST.has_key('load_teams'):
            sport_name = "hockey"
            league_name = "nhl"
            teams.team_data_retriever.TeamDataRetriever.load_teams(sport_name, league_name)
        if request.POST.has_key('load_images'):
            team_list = teams.models.Team.objects.all()
            for team in team_list:
                team.image_location = team.full_name().replace(' ','').replace('.','') + '.png'
                team.save()
    return render(request, "admin_actions.html")

loserpool/templates/admin_actions.html
{% extends "base.html" %}

{% block content %}
<ul>

<li><form action="{% url 'admin_actions' %}" method="post">
	{% csrf_token %}
	<input type="submit" name="load_teams" value="load load_teams" />
</form></li>

<li><form action="{% url 'admin_actions' %}" method="post">
	{% csrf_token %}
	<input type="submit" name="load_images" value="load_images" />
</form></li>

<li><form action="{% url 'admin_actions' %}" method="post">
	{% csrf_token %}
	<input type="submit" name="load_matchups" value="load matchups" />
</form></li>

</ul>
{% endblock %}

loserpool/templates/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static from staticfiles %}
	<link rel="stylesheet" href="{% static "base.css" %}">
	<title>{% block title %}NHL Loser Pool{% endblock %}</title>
</head>

<body>
	<div id="page">
		<div id="header">
			{% block header %}
			<p>
			{% if user.is_authenticated %}
			Welcome <a href="{% url 'user_options' %}">{{user}}</a>. <a href="{% url 'logout' %}">Sign out</a>
			{% else %}
			<a href="{% url 'login' %}">Sign in</a>
			{% endif %}
			</p>
			{% endblock %}
		</div>
	
		<div id="navigation">
			{% block navigation %}
			<ul>
				<li><a href="{% url 'index' %}">Home</a></li>
				<li><a href="{% url 'matchups:scoreboard' %}">Scoreboard</a></li>
				<li><a href="{% url 'matchups:submit_picks' %}">Submit Picks</a></li>
			</ul>
			{% endblock %}
		</div>
	
		<div id="content">
			{% block content %}Content{% endblock %}
		</div>
		
		<div id="footer">
			{% block footer %}©2013 Poolie{% endblock%}
		</div>
	</div>
</body>

</html>

loserpool/templates/change_password.html
{% extends "base.html" %}

{% block content %}
<div id="content-main">
<form action="" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    Please correct the error below.
    </p>
{% endif %}

<h1>Password change</h1>
<p>Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly.</p>
<div class="form">
    {{ form.old_password.errors }}
    <label for="id_old_password" class="required">Old password:</label>{{ form.old_password }}
</div>
<div class="form">
    {{ form.new_password1.errors }}
    <label for="id_new_password1" class="required">New password:</label>{{ form.new_password1 }}
</div>
<div class="form">
{{ form.new_password2.errors }}
    <label for="id_new_password2" class="required">Password (again):</label>{{ form.new_password2 }}
</div>
<div class="form">
    <input type="submit" value="Change password" class="default" />
</div>
</div>
</form></div>
{% endblock %}

loserpool/templates/index.html
{% extends "base.html" %}

{% block content %}

{% for blog in blog_posts %}
<div class="blog_post">

<div class="blog_title">
	<h1>{{blog.title}}</h1>
</div>

<div class="blog_date_time">
	<p>Posted on {{blog.date_time}}</p>
</div>

<div class="blog_author">
	<p>by {{blog.author}}</p>
</div>

<div class="blog_content">
	<p>{{blog.content}}</p>
</div>

</div>
{% endfor %}


{% endblock %}

loserpool/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>

{% if error_message %}
	<p>{{error_message}}</p>
{% endif %}
{% if user.is_authenticated %}
	<p>You are already logged in as {{user}}. <a href="{% url 'logout' %}">Logout</a></p> 
{% else %}
	{% if redirect_to %}
	<form action="{% url 'login' %}?next={{redirect_to}}" method="post">
	{% else %}
	<form action="{% url 'login' %}" method="post">
	{% endif %}

	{% csrf_token %}
		<div class="form">
		<p>Username {{login_form.username}}</p>
		</div>
		<div class="form">
		<p>Password {{login_form.password}}</p>
		</div>
		<div class="form">
		<input type="submit" value="Login" />
		</div>
	</form>
{% endif %}
{% endblock %}

loserpool/templates/password_changed.html
{% extends "base.html" %}

{% block content %}
<h1>Password change successful</h1>
<p>Your password was changed.</p>
{% endblock %}

loserpool/templates/successful_login.html
{% extends "base.html" %}

{% block content %}
<h1>Successfully logged in</h1>
{% endblock %}

loserpool/templates/successful_logout.html
{% extends "base.html" %}

{% block content %}
<h1>Successfully logged out</h1>
{% endblock %}

loserpool/templates/user_options.html
{% extends "base.html" %}

{% block content %}
<h1>Account Settings</h1>
<ul>
<li><a href="{% url 'password_change' %}">Change Password</a></li>

{% if perms.matchups.add_matchup %}
<li><a href="{% url 'matchups:update_current_scores' %}">Update Weekly Scores</a></li>
<li><a href="{% url 'matchups:admin_submit_picks_for_week' week_number user.id%}">Admin - Submit Picks</a></li>
<li><a href="{% url 'matchups:admin_scoreboard_for_week' week_number%}">Admin - Scoreboard</a></li>
{% endif %}
</ul>
{% endblock %}