loserpool/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from loserpool import views
import django.contrib.auth.views
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^matchups/', include('matchups.urls', namespace="matchups")),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^user_options/$', views.user_options, name='user_options'),
    url(r'^change_password/$', django.contrib.auth.views.password_change, {'template_name':'change_password.html'}, name='password_change'),
    url(r'^password_changed/$', django.contrib.auth.views.password_change_done, {'template_name':'password_changed.html'}),
    url(r'^admin_actions/$', views.admin_actions, name='admin_actions'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

)

matchups/urls.py
from django.conf.urls import patterns, url

from matchups.views import matchup_list, scoreboard, submit_picks, update_scores

urlpatterns = patterns('',
    url(r'^submit', submit_picks.submit_picks_for_current_matchup, name='submit_picks'),
    url(r'^(?P<week_number>\d+)/submit', submit_picks.submit_picks_for_week, name='submit_picks_for_week'),
    url(r'^(?P<week_number>\d+)/(?P<user_id>\d+)/admin_submit', submit_picks.admin_submit_picks_for_week, name='admin_submit_picks_for_week'),
    url(r'^(\d+)/admin_scoreboard', scoreboard.admin_scoreboard_for_week, name='admin_scoreboard_for_week'),
    url(r'^$', scoreboard.scoreboard_current_week, name='scoreboard'),
    url(r'^(\d+)/scoreboard', scoreboard.scoreboard, name='scoreboard_for_week'),
    url(r'^matchup$', matchup_list.current_matchups, name='current_matchups'),
    url(r'^(\d+)/matchup', matchup_list.weekly_matchups, name='weekly_matchups'),
    url(r'^update_scores', update_scores.update_current_scores, name='update_current_scores'),
    url(r'^(\d+)/update_scores', update_scores.update_scores_for_week, name='update_scores_for_week'),
)

teams/urls.py
from django.conf.urls import patterns, url

from teams import views

urlpatterns = patterns('',
    url(r'^$', views.team_manager, name='team_manager'),
)

matchups/models.py
from django.db import models
from teams.models import Team
from django.contrib.auth.models import User
from matchups.matchup_defs import CURRENT_TIMEZONE
import utilities
import pytz

class Matchup(models.Model):
    home_team = models.ForeignKey(Team, related_name="home_team")
    away_team = models.ForeignKey(Team, related_name="away_team")
    home_team_score = models.SmallIntegerField(default=-1)
    away_team_score = models.SmallIntegerField(default=-1)
    date_time = models.DateTimeField()
    
    def date_time_string(self):
        fmt = "%A, %b %d - %I:%M %p"
        return self.date_time.astimezone(pytz.timezone(CURRENT_TIMEZONE)).strftime(fmt)
    
    def full_name(self):
        return self.date_time_string() + ' - ' + self.away_team.full_name() + ' at ' + self.home_team.full_name()
    
    def __unicode__(self): 
        return self.full_name()
    
    def winning_team(self):
        if self.home_team_score < 0 or self.away_team_score < 0:
            return None
        if self.home_team_score > self.away_team_score:
            return self.home_team
        else:
            return self.away_team
    
class PickSet(models.Model):
    user = models.ForeignKey(User)
    letter_id = models.CharField(default='A', max_length='32')
    
    def __unicode__(self):
        if self.user.first_name:
            return self.user.first_name + " - " + self.letter_id
        return self.user.username + " - " + self.letter_id
    
    def is_eliminated(self):
        pick_values = Pick.objects.filter(pick_set__id=self.id).values_list('is_winning_pick', flat=True)
        picked_wrong = True in pick_values 
        minimum_number_of_picks = int(utilities.current_week_number())-1
        missed_a_week = Pick.objects.filter(pick_set__id=self.id).count() < minimum_number_of_picks
        return picked_wrong or missed_a_week

class Pick(models.Model):
    selected_team = models.ForeignKey(Team)
    week_number = models.SmallIntegerField(default=-1)
    pick_set = models.ForeignKey(PickSet)
    is_winning_pick = models.BooleanField(default=False)
    def __unicode__(self): 
        return str(self.pick_set)+ " - Week " + str(self.week_number)

matchups/forms.py
from matchups.models import Pick, Matchup
from matchups import model_utilities
from django import forms

class PickForm(forms.ModelForm):
    class Meta:
        model = Pick
        fields = {'selected_team'}
    def __init__(self, *args, **kwargs):
        super(PickForm, self).__init__(*args, **kwargs)
        widget_choices = [('','')]
        if self.instance:
            week_number = self.instance.week_number 
            previously_selected_teams = Pick.objects.filter(pick_set=self.instance.pick_set).exclude(week_number=week_number).values_list('selected_team', flat=True)
            team_choices = model_utilities.get_list_of_choices_for_week(week_number)
            for team in team_choices:
                if team.id not in previously_selected_teams:
                    widget_choices.append((team.id, team.full_name()))
        self.fields['selected_team'].widget.choices = widget_choices
        pick_label = "Loser pick " + str(self.instance.pick_set.letter_id)
        self.fields['selected_team'].label = pick_label
        
class MatchupForm(forms.ModelForm):
    class Meta:
        model = Matchup
        fields = {'home_team_score', 'away_team_score'}

matchups/views/matchup_list.py
from django.shortcuts import render
from matchups import model_utilities, utilities

def current_matchups(request):
    return weekly_matchups(request, utilities.current_week_number())

def weekly_matchups(request, week_number):
    if int(week_number) < 1:
        context = {'date_range' : 'Week number is invalid'}
        return render(request, 'matchup_list.html', context)
    matchup_list = model_utilities.matchups_for_week(week_number)
    date = str(utilities.game_day(week_number).strftime("%b %d, %Y"))
    context = {'matchup_list' : matchup_list,
               'date_range' : date,}
    return render(request, 'matchup_list.html', context)

matchups/views/scoreboard.py
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required
from matchups import utilities, model_utilities
from matchups.models import PickSet
    
@permission_required('matchups.add_matchup')
def admin_scoreboard_for_week(request, week_number):
    return scoreboard(request, week_number, True)

def scoreboard_current_week(request):
    return scoreboard(request, utilities.current_week_number())
    
def scoreboard(request, week_number, is_admin=False):
    pick_sets = PickSet.objects.prefetch_related('pick_set')
    week_has_started = model_utilities.has_first_matchup_of_week_started(week_number)
    current_week = int(utilities.current_week_number())
    
    row_sets = dict()
    for pick_set in pick_sets:
        pick_user = pick_set.user
        row_set = get_or_create_row_set(row_sets, pick_user, request.user)
        row_set.rowspan += 1
        picks = pick_set.pick_set.all()
        table_row = PickRow()
        table_row.letter_id = pick_set.letter_id
        table_row.pick_row_items = list()
        pick_set_is_eliminated = False
        number_of_picks = 0
        for pick in picks:
            number_of_picks += 1
            row_item = PickRowItem()
            row_item.show_pick = is_admin or row_set.is_current_user or week_has_started or pick.week_number != current_week
            row_item.is_winning_pick = pick.is_winning_pick
            pick_set_is_eliminated |= row_item.is_winning_pick 
            row_item.team_image_location = pick.selected_team.image_location
            row_item.team_name = pick.selected_team.full_name()
            table_row.pick_row_items.append(row_item)
        minimum_number_of_picks = int(utilities.current_week_number())-1
        missed_a_week = number_of_picks < minimum_number_of_picks
        pick_set_is_eliminated |= missed_a_week
        table_row.pick_set_is_eliminated = pick_set_is_eliminated
        row_set.user_is_eliminated &= pick_set_is_eliminated
        for i in range(0, current_week-len(table_row.pick_row_items)):
            row_item = PickRowItem()
            row_item.is_unavailable = table_row.pick_set_is_eliminated
            table_row.pick_row_items.append(row_item)
        row_set.pick_rows.append(table_row)
    ordered_row_sets = list()
    eliminated_row_sets = list()
    for row_set in row_sets.values():
        if row_set.user_is_eliminated:
            eliminated_row_sets.append(row_set)
        elif row_set.is_current_user:
            ordered_row_sets.insert(0, row_set)
        else:
            ordered_row_sets.append(row_set)
    ordered_row_sets.extend(eliminated_row_sets)
    week_date = str(utilities.game_day(week_number).strftime("%b %d, %Y"))
    context = {'current_week': current_week,
               'selected_week': int(week_number),
               'week_date': week_date,
               'row_sets':ordered_row_sets}
    return render(request, 'scoreboard.html', context)

def get_or_create_row_set(row_sets, user, current_user):
    if not row_sets.has_key(user):
        row_sets[user] = RowSet()
        row_sets[user].user_name = user_display_name(user)
        row_sets[user].pick_rows = list()
        row_sets[user].is_current_user = current_user == user
    return row_sets[user]

def user_display_name(user):
    if user.first_name:
        return user.first_name
    return user.username

class RowSet:
    rowspan = 0
    user_is_eliminated = True
    user_name = None
    pick_rows = list()
    is_current_user = False

class PickRow:
    pick_set_is_eliminated = False
    letter_id = 'A'
    pick_row_items = list()
    
class PickRowItem:
    show_pick = False
    is_winning_pick = False
    team_image_location = ''
    team_name = ''
    is_unavailable = False
    

matchups/views/submit_picks.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from matchups import utilities
from matchups import model_utilities
from django.contrib.auth.models import User
from matchups.forms import PickForm
from matchups.models import Pick

def submit_picks_for_current_matchup(request):
    return submit_picks_for_week(request, utilities.current_week_number())

@permission_required('matchups.add_matchup')
def admin_submit_picks_for_week(request, week_number, user_id):
    user = get_object_or_404(User, id=user_id)
    return submit_picks_for_user(request, week_number, user, True)

@login_required
def submit_picks_for_week(request, week_number):
    return submit_picks_for_user(request, week_number, request.user)

@login_required
def submit_picks_for_user(request, week_number, user, is_admin = False):
    if request.method =="POST" and request.POST.has_key('user_select'):
        selected_username = request.POST.get('user_select')
        selected_user = User.objects.get(username=selected_username)
        return redirect('matchups:admin_submit_picks_for_week', week_number=week_number, user_id=selected_user.id)
    week_date = str(utilities.game_day(week_number).strftime("%b %d, %Y"))
    matchup_list = None
    form_list = list()
    error_message = ''
    if model_utilities.has_first_matchup_of_week_started(week_number) and not is_admin:
        error_message = 'Cannot change picks, first game of the week has already started.'
    else:
        matchup_list = model_utilities.matchups_for_week(week_number)
        pick_sets = model_utilities.pick_sets_for_user(user)
        failed_to_save_field = False
        all_picks_are_eliminated = True
        for pick_set in pick_sets:
            if not pick_set.is_eliminated():
                all_picks_are_eliminated = False
            form, failed_to_save = create_or_get_form_for_pick(request, week_number, pick_set)
            form_list.append(form)
            if failed_to_save:
                failed_to_save_field = True
        if failed_to_save_field:
            error_message = 'Failed to save picks. See below for details.'
        if all_picks_are_eliminated and not is_admin:
            form_list = list()
            error_message = 'Sorry, All picks have been eliminated.'
    context = {'matchup_list' : matchup_list,
               'form_list' : form_list,
               'error_message' : error_message,
               'week_number': int(week_number),
               'submitted_picks': request.method=="POST",
               'week_date' : week_date,
               'users' : User.objects.all(),
               'weeks' : range(1,utilities.current_week_number()+2),
               'submit_user' : user,
               'is_admin' : is_admin}
    return render(request, 'submit_picks.html', context)

def create_or_get_form_for_pick(request, week_number, pick_set):
    failed_to_save_field = False
    pick = model_utilities.get_or_create_pick(week_number, pick_set)
    if request.method == "POST":
        form = PickForm(request.POST, prefix=pick_set.id, instance=pick)
        if form.is_valid():
            form.save()
        elif not pick_set.is_eliminated():
            failed_to_save_field = True
        picks = Pick.objects.filter(week_number=week_number, pick_set=pick_set)
        model_utilities.update_winning_picks_for_week(week_number, picks)
    else:
        form = PickForm(prefix=pick_set.id, instance=pick)
    return form, failed_to_save_field

matchups/views/update_scores.py
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required
from matchups.forms import MatchupForm
from matchups import utilities, model_utilities
from matchups.models import Pick

def update_current_scores(request):
    return update_scores_for_week(request, utilities.current_week_number())

@permission_required('matchups.add_matchup')
def update_scores_for_week(request, week_number):
    weeks = range(1,utilities.current_week_number()+2)
    week_date = str(utilities.game_day(week_number).strftime("%b %d, %Y"))
    forms = list()
    matchup_list = model_utilities.matchups_for_week(week_number)
    for matchup in matchup_list:
        forms.append(create_form_for_matchup_scores(matchup, request))
    if request.method =="POST":
        picks = Pick.objects.filter(week_number=week_number)
        model_utilities.update_winning_picks_for_week(week_number, picks)
    context = {'weeks': weeks,
               'selected_week': int(week_number),
               'week_date': week_date,
               'forms': forms}
    return render(request, 'update_scores.html', context)

def create_form_for_matchup_scores(matchup, request):
    if request.method == "POST":
        matchup_form = MatchupForm(request.POST, instance=matchup, prefix=matchup.id)
        if matchup_form.is_valid():
            matchup_form.save()
    else:
        matchup_form = MatchupForm(instance=matchup, prefix=matchup.id)
    return matchup_form

matchups/templates/matchup_list.html
{% extends "base.html" %}

{% block content %}
<h1>Matchups</h1>

{% if date_range %}
	<h2>{{date_range}}</h2>
{% endif %}

{% if matchup_list %}
	<table>
		<tr>
			<th>Date</th>
			<th>Home team</th>
			<th>Home score</th>
			<th>Away team</th>
			<th>Away score</th>
		</tr>
		{% for matchup in matchup_list %}
		<tr>
			<td>{{matchup.date_time_string}}</td>
			<td>{{matchup.home_team}}</td>
			<td>
			{% if matchup.home_team_score >= 0 %}
				{{matchup.home_team_score}}
			{% endif %}
			</td>
			<td>{{matchup.away_team}}</td>
			<td>
			{% if matchup.away_team_score >= 0 %}
				{{matchup.away_team_score}}
			{% endif %}
			</td>
		</tr>
		{% endfor %}
	</table>
{% else %}
	<p>No matchups are available</p>
{% endif %}
{% endblock %}

matchups/templates/scoreboard.html
{% extends "base.html" %}
{% load matchup_template_extras %}
{% block content %}
<div id="content_title">
<h1>Scoreboard <em>Week {{selected_week}} - {{week_date}}</em></h1>
</div>

<div id="scoreboard_table">
<table>
	<tr>
		<th>Team</th>
		<th>Pick</th>
		{% for week_number in current_week|get_range %}
		<th>Week {{week_number|add:"1"}}</th>
		{% endfor %}
	</tr>
	{% for row_set in row_sets %}
	<tr>
		<td rowspan="{{ row_set.rowspan }}">
		<div class="user_name"><h5{% if row_set.user_is_eliminated %} class="eliminated_user"{% endif %}>{{row_set.user_name}}</h5></div>
		</td>
		
		{% for table_row in row_set.pick_rows %}
			{% if table_row.letter_id != 'A' %}
				<tr>
			{% endif %}
			<td>
			<h5{% if table_row.pick_set_is_eliminated %} class="eliminated_set"{% endif %}>{{table_row.letter_id}}</h5>
			</td>
			{% for pick in table_row.pick_row_items %}
				{% if pick.is_unavailable %}
					<td class="eliminated_pick"></td>
				{% elif not pick.show_pick %}
					<td></td>
				{% else %}
					<td class="pick_cell">
					<div{% if pick.is_winning_pick %} class="winning_pick"{% endif %}>
					<img src="{{STATIC_URL}}{{pick.team_image_location}}"/>
					<p>{{pick.team_name}}</p>
					</div></td>
				{% endif %}
			{% endfor %} 
			</tr>
		{% endfor %}
	{% endfor %}
</table>
</div>
{% endblock %}

matchups/templates/submit_picks.html
{% extends "base.html" %}

{% block content %}
<div id="content_title">
{% if is_admin %}
<h1>Submitting picks for {{submit_user}}
{% else %}
<h1>Submit Picks 
{% endif %}
<em> Week {{week_number}} - {{week_date}}</em></h1>
</div>

{% if is_admin %}
<p>Week number:</p>
	{% for week in weeks %}
		{% if week_number == week %}
			{{week_number}}
		{% else %}
			<a href="{% url 'matchups:admin_submit_picks_for_week' week submit_user.id%}">{{week}}</a>
		{% endif %}
	{% endfor %}

<p>Select User</p>
<form id="user_selection_form" action="{% url 'matchups:admin_submit_picks_for_week' week_number submit_user.id %}" method="post">
{% csrf_token %}
<select id='user_selection' name='user_select'>
{% for user_option in users %}
{% if user_option == submit_user %}
<option selected>{{user_option}}</option>
{% else %}
<option>{{user_option}}</option>
{% endif %}
{% endfor %}
</select>
</form>
{% endif %}

<script>
var handleChange = function(event){
var form = document.querySelector('#user_selection_form');
form.submit();
}
var selector = document.querySelector('#user_selection');
selector.addEventListener('change', handleChange);
</script>

<div id="prompt">
{% if not error_message and submitted_picks %}
	<div class='submitted_picks'>
	Successfully submitted picks
	</div>
{% endif %}
{% if error_message %}
	<div class='error_message'>
	{{error_message}}
	</div>
{% endif %}
</div>

{% if form_list %}
<div id="pick_block">
<h3>Picks</h3>	
	{% if is_admin %}
		<form action="{% url 'matchups:admin_submit_picks_for_week' week_number submit_user.id %}" method="post">
	{% else %}
		<form action="{% url 'matchups:submit_picks_for_week' week_number %}" method="post" name="nme1">
	{% endif %}
	{% csrf_token %}
	{% for form in form_list %}
	<div class="form">
		<h4>{{form.selected_team.label}}</h4>
		{% if form.instance.pick_set.is_eliminated %}
			<p>Eliminated</p>
		{% else %}
			<p>{{form.selected_team.errors}}</p>
			<p>{{form.selected_team}}</p>
		{% endif %}
	</div>
	{% endfor %}
		<div id="submit_button">
		<input type="submit" value="Submit picks" id="submit" name="submit_picks"/>
		</div>
		</form>
{% else %}
	<p>No matchups available</p>
{% endif %}
</div>

<div id="matchup_block">
<h3>Matchups for Saturday, {{week_date}}</h3>
<table>
<tr><th>Away Team</th><th>Home Team</th></tr>
{% for matchup in matchup_list %}
<tr>
<td class="pick_cell">
<div class="team_icon">
<img src="{{STATIC_URL}}{{matchup.away_team.image_location}}"/>
<p>{{matchup.away_team}}</p>
</div></td>
<td class="pick_cell">
<div class="team_icon">
<img src="{{STATIC_URL}}{{matchup.home_team.image_location}}"/>
<p>{{matchup.home_team}}</p>
</div></td>
</tr>
{% endfor %}
</table>
</div>

{% endblock %}

matchups/templates/update_scores.html
{% extends "base.html" %}

{% block content %}
<div id="content_title">
<h1>Update Scores <em>Week {{selected_week}} - {{week_date}}</em></h1>
</div>

<p>Week number:</p>
{% for week_number in weeks %}
{% if selected_week == week_number %}
{{week_number}}
{% else %}
<a href="{% url 'matchups:update_scores_for_week' week_number %}">{{week_number}}</a>  
{% endif %}
{% endfor %}

<div id="update_scores">
<form action="{% url 'matchups:update_scores_for_week' selected_week %}" method="post">
{% csrf_token %}
{% for form in forms %}
<div class="matchup_label">{{form.instance.full_name}}</div>
<div class="form">
{{form.instance.away_team}}: {{form.away_team_score}}        {{form.instance.home_team}}: {{form.home_team_score}}
</div>
{% endfor %}
<div id="submit_button">
	<input type="submit" value="Update scores" id="submit"/>
</div>
</form>
</div>

{% endblock %}